#!/usr/bin/env php
<?php
require 'vendor/autoload.php';

use Julian\ToyRobotApp\ToyRobot\ToyRobot;
use Julian\ToyRobotApp\Generic\Table;
use Julian\ToyRobotApp\ToyRobot\ToyRobotCommandQueue;

$robot = new ToyRobot();
$table = new Table(5, 5);
$commandQueue = new ToyRobotCommandQueue($robot, $table);

$inputFile = $argv[1];
if(isset($inputFile) && trim($inputFile) != '') {
    $commandQueue->importCommandsFromFile($inputFile);
    $commandQueue->invokeCommands();
}